name: Deploy Spring Boot to GCP

on:
  push:
    branches: [ "master", "main" ]
    paths:
      - 'asset/**'
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'


      - name: Build with Maven
        run: |
          cd asset
          chmod +x mvnw
          ./mvnw clean package -DskipTests


      - name: Deliver Boot Jar to GCP
        uses: appleboy/scp-action@1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          source: "asset/target/asset-0.0.1-SNAPSHOT.jar"
          target: "~/"
          strip_components: 2 

      - name: Execute Server Reload via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            CURRENT_PID=$(lsof -t -i:8080)
            if [ -z "$CURRENT_PID" ]; then
              echo "No running application found on port 8080."
            else
              echo "Killing running application on PID: $CURRENT_PID"
              kill -15 $CURRENT_PID
              sleep 5
            fi
            
            mv ~/target/asset-0.0.1-SNAPSHOT.jar ~/asset-0.0.1-SNAPSHOT.jar || true
            rm -rf ~/target
            echo "${{ secrets.ENV_FILE_CONTENT }}" > ~/key.env
            nohup java -Xmx350m -jar ~/asset-0.0.1-SNAPSHOT.jar > ~/nohup.out 2>&1 &
          
            echo "Spring Boot Application deployed successfully!"
